### ISSUE TITLE
Bioconductor:preprocessCore   quantile normalization

### ISSUE THREAD

**Issue by kanchanhole** [bmbolstad/preprocessCore#3] opened 2018-03-22 15:23 UTC
Hello,

I  have used Bioconductor ‘preprocessCore’ for quantile normalization. I am trying t understand how does it work with low expressed or zero count genes.Could you provide more information on it?
TIA

**Comment by bmbolstad** [comment] 2018-03-22 17:56
This is not really an issue with the software. Or at least not a bug report or feature request. So I am going to close this issue.

For questions like this I suggest the BioConductor support site.  https://support.bioconductor.org/.  For one you are likely to get answers from multiple people, rather than just me, and secondly that is the place to ask questions about the software and use of the software.

**Closed as completed by bmbolstad** 2018-03-22 17:56 UTC

**Comment by kanchanhole** [comment] 2018-03-22 18:02
Thank you and apologies
